name: kaptan_asistani
description: Kaptan Asistani - Denizcilik Seyir Asistani
publish_to: "none"
version: 1.3.1+9

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_map: 6.1.0
  latlong2: 0.9.1
  geolocator: 10.1.0
  http: 1.2.0
  shared_preferences: 2.2.2
  web_socket_channel: 2.4.0
  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#06141F"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
