name: kaptan_asistani
description: Kaptan Asistani - Denizcilik Seyir Asistani
publish_to: "none"
version: 1.0.2+3

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_map: 6.1.0
  latlong2: 0.9.1
  geolocator: 10.1.0
  http: 1.2.0
  shared_preferences: 2.2.2
  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
